config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'projects#index'

  resources :projects do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :tasks

  validates :name, presence: true,
                   length: { maximum: 255 }

  before_destroy :destroy_tasks

  private

  def destroy_tasks
    tasks.destroy_all
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project

  enum status: {todo: 0, in_progress: 1, code_review: 2, done: 3}
  enum priority: {low: 0, normal: 1, high: 2}

  validates :name, presence: true,
                   length: {maximum: 255}
  validates :status, presence: true
  validates :priority, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_projects
  has_many :projects, through: :user_projects
  has_many :tasks

  before_save { self.email = email.downcase }
  before_destroy :destroy_tasks

  validates :user_name, presence: true,
                        length: {maximum: 50}
  validates :first_name, presence: true, 
                         length: {maximum: 50},
                         format: { with: /[\p{L}\p{Pd}.]/ }
  validates :last_name, presence: true, 
                        length: {maximum: 50},
                        format: { with: /[\p{L}\p{Pd}.]/ }
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  private
    def destroy_tasks
      self.tasks.destroy_all
    end
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project

  enum role: {developer: 0, manager: 1, owner: 2}

  validate :is_unique?

  protected
    def is_unique?
      duplicate = UserProject.find_by(user_id: self.user_id, project_id: self.project_id)
      return duplicate
    end

  private
    def destroy_tasks
      self.tasks.destroy_all
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if:  :devise_controller?

  def after_sign_in_path_for(resource)
    projects_path  
  end

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_name])

  end

  private
  
  def user_not_authorized
    flash[:alert] = "Nie masz uprawnień do wyświetlania tej strony"
    redirect_to root_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:destroy, :edit, :update, :show]
  before_action :authenticate_user!
  
  # GET /projects
  def index
    @projects = current_user.projects
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/:id
  def show
    @user_projects = set_user_projects
  end

  # GET /projects/:id/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    if @project.save
      add_user_to_project
      redirect_to projects_path, notice: "Project created"
    else
      render action: 'new'
    end
  end

  # DELETE /projects/:id
  def destroy
    @project.destroy
    redirect_to projects_path
  end
  

  # PATCH/PUT /projects/:id
  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: "Project updated"
    else
      render action: 'edit'
    end
  end
  
  private
    def add_user_to_project
      UserProject.create(user_id: current_user.id, project_id: @project.id, role: :owner)  
    end

    def set_user_projects
      @project_users = UserProject.where(project_id: @project.id)
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy, :edit, :update, :show]
  before_action :authenticate_user!
  
  # GET projects/:project_id/tasks
  def index
    @project = Project.find(params[:project_id])
    @tasks = Task.where(user_id: current_user.id, project_id: @project.id)
  end

  # GET projects/:project_id/tasks/new
  def new
    @project = Project.find(params[:project_id])
    @task = Task.new
  end
  
  # GET projects/:project_id/tasks/:id/edit
  def edit
    @project = set_project
  end

  # POST projects/:project_id/tasks
  def create
    @task = Task.new(task_params)
    @task.project_id = set_project.id
    @task.user_id = current_user.id
    if @task.save
      redirect_to project_tasks_path, notice: "Task created"
    else
      render action: 'new'
    end
  end

  # GET projects/:project_id/tasks/:id
  def show
    @project = set_project
  end

  # DELETE projects/:project_id/tasks/:id
  def destroy
    @task.destroy
    redirect_to project_tasks_path
  end

  # PATCH/PUT /projects/:project_id/tasks/:id
  def update
    if @task.update(task_params)
      redirect_to project_tasks_path, notice: "Task updated"
    else
      render action: 'edit'
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :status, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    %nav
      .navbar-header
        = link_to "ProjectIT", root_path, id: "logo"
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Back", :back, id: "redirected_nav"
        %li
          - if user_signed_in?
            = link_to "Logout", destroy_user_session_path, :method => :delete, id: "redirected_nav"
        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProjectIT
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = render 'layouts/header'
    %div.content
      = yield

app/views/projects/_form.html.haml
.padding
  .row
    .col-md-6
      = simple_form_for @project do |f|
        = f.input :name, label: 'Name', error: "Required length: 1-255 signs"
        = f.input :description, label: "Description"
        = f.submit "Submit", class: "btn btn-success"

app/views/projects/edit.html.haml
%h1 Edit project
= render 'form'

app/views/projects/index.html.haml
%h1 Projects

.actions
  = link_to 'Add project', new_project_path, :class => "btn btn-success", data: { "no-turbolink" =>  true}

%table.table
  %thead
    %tr
      %th Go to tasks
      %th Go to description
    
  %tbody
    - @projects.each do |project|
      %tr
        %td.text
          %span= link_to project.name, project_tasks_path(project.id)
        %td.text
          %span= link_to project.description, project
        %td= link_to 'Edit', edit_project_path(project), data: { "no-turbolink" =>  true}
        %td= link_to 'x', project, method: :delete, data: { confirm: 'Na pewno usunąć?' }, class: "close"

app/views/projects/new.html.haml
%h1 New project
= render 'form'

app/views/projects/show.html.haml
%h1= @project.name
%h3= @project.description

- if @user_projects
  %h3= "Users in project:"
  %table.table
    %thead
      %tr
        %th User Name
        %th First Name
        %th Last Name
        %th E-mail
      
    %tbody
      - @user_projects.each do |user_project|
        %tr
          %td= user_project.user.user_name
          %td= user_project.user.first_name
          %td= user_project.user.user_name
          %td= user_project.user.email
    

app/views/tasks/_form.html.haml
.padding
  .row
    .col-md-6
      = simple_form_for [@project, @task] do |f|
        = f.input :name, label: 'Name', error: "Required length: 1-255 signs"
        = f.input :description, label: "Description"
        = f.input :status, include_blank: false
        = f.input :priority, include_blank: false
        = f.submit "Submit", class: "btn btn-success"

app/views/tasks/edit.html.haml
%h1 Edit task for #{@project.name}
= render 'form'

app/views/tasks/index.html.haml
%h1 Tasks for #{@project.name}

.actions
  = link_to 'Add task', new_project_task_path, :class => "btn btn-success", data: { "no-turbolink" =>  true}

- (0..3).each do |status|
  - tasks_statused = @tasks.where(status: status)
  - if tasks_statused.length > 0
    %h2= tasks_statused.first.status.humanize
    %table.table
      %thead
        %tr
          %th Name
          %th Description
          %th Priority
        
      %tbody
        - tasks_statused.each do |task|
          %tr
            %td.text
              %span= link_to task.name, project_task_path(@project, task)
            %td.text
              %span= link_to task.description, project_task_path(@project, task)
            %td= task.priority.humanize 
            %td= link_to 'Edit', edit_project_task_path(@project, task), data: { "no-turbolink" =>  true}
            %td= link_to 'x', project_task_path(@project, task), method: :delete, data: { confirm: 'Na pewno usunąć?' }, class: "close"

app/views/tasks/new.html.haml
%h1 New task for #{@project.name}
= render 'form'

app/views/tasks/show.html.haml
%h1 Task: #{@task.name}
%h1 Project: #{@project.name}
%h1 Status: #{@task.status.humanize}
%h1 Priority: #{@task.priority.humanize}
%h3= @task.description